networks:
  ciapol-network:
    driver: bridge

volumes:
  pulsar-data:
  minio-data:
  postgres-data:
  redis-data:

services:
  # Zookeeper pour Pulsar
  zookeeper:
    image: apachepulsar/pulsar:2.10.6
    container_name: ciapol-zookeeper
    restart: unless-stopped
    networks:
      - ciapol-network
    ports:
      - "2181:2181"
    environment:
      - PULSAR_MEM=-Xms512m -Xmx512m
    command: >
      bash -c "bin/pulsar zookeeper"
    volumes:
      - pulsar-data:/pulsar/data

  # Pulsar Broker
  pulsar-broker:
    image: apachepulsar/pulsar:2.10.6
    container_name: ciapol-pulsar-broker
    restart: unless-stopped
    networks:
      - ciapol-network
    ports:
      - "6650:6650"
      - "3000:8080"
    environment:
      - PULSAR_MEM=-Xms1g -Xmx1g
    depends_on:
      - zookeeper
    command: >
      bash -c "bin/pulsar broker"
    volumes:
      - pulsar-data:/pulsar/data

  # MinIO pour stockage objet
  minio:
    image: minio/minio:latest
    container_name: ciapol-minio
    restart: unless-stopped
    networks:
      - ciapol-network
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=ciapol-admin
      - MINIO_ROOT_PASSWORD=ciapol-password-2024
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

  # PostgreSQL pour métadonnées
  postgres:
    image: postgres:14
    container_name: ciapol-postgres
    restart: unless-stopped
    networks:
      - ciapol-network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ciapol_db
      - POSTGRES_USER=ciapol_user
      - POSTGRES_PASSWORD=ciapol_pass_2024
      - POSTGRES_INITDB_ARGS=--encoding=UTF8 --lc-collate=C --lc-ctype=C
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./infrastructure/postgres/init:/docker-entrypoint-initdb.d

  # Redis pour cache
  redis:
    image: redis:7-alpine
    container_name: ciapol-redis
    restart: unless-stopped
    networks:
      - ciapol-network
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass ciapol-redis-2024
    volumes:
      - redis-data:/data

  # Next.js Frontend
  nextjs-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ciapol-frontend
    restart: unless-stopped
    networks:
      - ciapol-network
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_WEBSOCKET_URL=ws://localhost:8000/ws
      - TZ=Africa/Abidjan
    depends_on:
      - postgres
      - redis
      - minio
      - pulsar-broker